name = "SphericalOperators"
uuid = "0740b0f4-c400-11e8-2cb9-2f360bf4d2ec"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
LiterateOrg = "93c33440-6125-11e8-0ffd-df540d4e821e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
